### ISSUE TITLE
html filename not the same as the templ filename

### ISSUE THREAD

**Issue by indaco** [nokacper24/static-templ#3]
I expected the generated HTML filename to match that of its corresponding template file, but that is not the case.

The current implementation generates the HTML filename "based on the original function name".

https://github.com/nokacper24/static-templ/blob/9b082e6c04962682de6395542811beaaf90178a0/internal/finder/finder.go#L96-L103

**Comment by nokacper24** [comment]
That's right, the html filename is based on the exported component name. This is because you can have multiple templ components in a single file, thus they'd all override each other if written to the same file.

unless I am missing something and you have a better suggestion?

I completely understand why you'd assume the filename would be kept the same. I think this was my original thought as well, it would be consistent with the paths being mirrored... it's just the case I described above that would potentially cause issues.

How about sticking to the same filename by default, but falling back to component names in case there is multiple defined in the same file? Alternatively it could error out if there is multiple exported components in a single file, simply not supporting it.

Also, sorry for late reply, did not realize anything was happening here! I'm happy to merge your PRs, just want to resolve the issue above first.

**Comment by indaco** [comment]
"How about sticking to the same filename by default, but falling back to component names in case there is multiple defined in the same file? Alternatively it could error out if there is multiple exported components in a single file, simply not supporting it."

Make sense. 

What do you think if the file name whatever it is based on, follows a  slug format?

E.g. component function name "HelloWorld" then "hello-world.html"?

**Comment by nokacper24** [comment]
okay i think we should do my first suggestion then, also filename by default but fallback to function names in case there is multiple. 

And yes, slug format seems like the best fit. ([this](https://github.com/gobeam/Stringy?tab=readme-ov-file#kebabcaserule-string-stringmanipulation) looks useful here)

I can get this done later today or tomorrow. Unless you want to do it then feel free, just let me know asap so we don't double the work.

Also, since we agree on this I can maybe just approve the PRs the way they are at the moment and just apply these changes afterwards?

**Comment by indaco** [comment]
Works for me, we agreed on the approach

I cannot start working on it before after tomorrow night. Feel free to start if you have bandwidth for that 


To slugify, your suggestion is ok or we can write a simple function with the constraint that input strings are valid Go function names too

**Comment by nokacper24** [comment]
done what we discussed in c3b2e8d2d6760c06d8e4903b78dfe4deeaf88e46  
and slugified filenames in 232b14ac96fbf37b8d07af6b08216107550f9779, used the module I linked as I'm lazy and it gets the job done

Again, thanks for contributing and using this tool!! Love to see somebody actually use the thing I made :)

**Comment by indaco** [comment]
@nokacper24 Great! Thanks for accepting my PRs and for the opportunity to work together on this.
